package org.ventanas;

import Data.Variables;

import javax.swing.*;

import static Data.FuncionesEnlace.*;
import static Data.FuncionesEnlace.registrarUnUsuario;
import static Funciones_BBDD.FuncionesComprobacion.comprobacionFormatoCorreo;
import static Funciones_BBDD.FuncionesComprobacion.comprobacionFormatoTelef;

public class RegistrarEmpleado extends javax.swing.JFrame{
    private GestionarEmpleados ventanaPrincipal;

    /**
     * Creates new form Register
     */
    public RegistrarEmpleado(GestionarEmpleados parent) {
        this.ventanaPrincipal = parent;
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        salirButton = new javax.swing.JToggleButton();
        nombreText = new javax.swing.JLabel();
        apellidoText = new javax.swing.JLabel();
        correoText = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        telefonoText = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        registrarButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        passwordText = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        errorText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(525, 425));

        salirButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salirButton.setText("X");
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });

        nombreText.setText("Nombre:");

        apellidoText.setText("Apellido:");

        correoText.setText("Correo:");


        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        telefonoText.setText("Telefono:");

        registrarButton.setText("Registrar");

        volverButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        volverButton.setText("<");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        passwordText.setText("Contraseña:");

        errorText.setForeground(new java.awt.Color(255, 0, 0));
        errorText.setText("xd");
        errorText.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(volverButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salirButton))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(registrarButton)
                                .addGap(98, 98, 98))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(errorText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(86, 86, 86))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nombreText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(apellidoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(telefonoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(correoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(21, 21, 21)
                                                                .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(correo, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                                        .addComponent(apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                                        .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                                                                        .addComponent(password))))
                                                .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(salirButton)
                                        .addComponent(volverButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nombreText)
                                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(apellidoText)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(correoText)
                                        .addComponent(correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(telefonoText)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordText)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(errorText)
                                .addGap(26, 26, 26)
                                .addComponent(registrarButton)
                                .addGap(0, 104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {
        salirPrograma();
    }

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String correoS = correo.getText();
        char[] contraAux = password.getPassword();
        String contraS = new String(contraAux);
        java.util.Arrays.fill(contraAux, ' ');
        String nombreS = nombre.getText();
        String apellidoS = apellido.getText();
        String telefonoS = telefono.getText();
        if (correoS.isEmpty() && contraS.isEmpty() && nombreS.isEmpty() && apellidoS.isEmpty() && telefonoS.isEmpty()) {
            errorText.setText("Por favor, rellene todos los campos para continuar");
            errorText.setVisible(true);
            return;
        }
        if (!comprobacionFormatoCorreo(correoS)) {
            errorText.setText("El correo no tiene un formato valido");
            errorText.setVisible(true);
            return;
        }
        if (!comprobacionFormatoTelef(telefonoS)) {
            errorText.setText("El telefono no tiene un formato valido");
            errorText.setVisible(true);
            return;
        }
        if (!comprobacionDisponibilidadDeCorreoUsuario(correoS)) {
            errorText.setText("El correo no esta disponible para registrarlo");
            errorText.setVisible(true);
            return;
        }
        if (!comprobacionDisponibilidadDeTelefonoUsuario(telefonoS)) {
            errorText.setText("El telefono no esta disponible para registrarlo");
            errorText.setVisible(true);
            return;

        }
        annadirEmpleadoGerente(nombreS, apellidoS, correoS, telefonoS, contraS,conseguirLugarTrabajoEmpleado(conseguirIDExtra(Variables.usuario,Variables.telefono,Variables.password)));
        errorText.setVisible(false);
        JOptionPane.showMessageDialog(null, "El registro del empleado ha sido exitoso :)", "Información", JOptionPane.INFORMATION_MESSAGE);
        volverVentanaAnterior();
    }


    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        ventanaPrincipal.setVisible(true);
    }

    private void volverVentanaAnterior() {
        this.setVisible(false);
        ventanaPrincipal.setVisible(true);
        ventanaPrincipal.UpdateVentana();
    }


    // Variables declaration - do not modify
    private javax.swing.JTextField apellido;
    private javax.swing.JLabel apellidoText;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel correoText;
    private javax.swing.JLabel errorText;
    private javax.swing.JButton registrarButton;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel nombreText;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordText;
    private javax.swing.JToggleButton salirButton;
    private javax.swing.JTextField telefono;
    private javax.swing.JLabel telefonoText;
    private javax.swing.JButton volverButton;
}
